Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -71,14 +71,14 @@ stages:
           echo "Listing all files in $(Build.SourcesDirectory)"
           ls -R $(Build.SourcesDirectory)
 
-          echo "ls alh"
-          ls -alh .
+          # echo "ls alh"
+          # ls -alh .
 
-          echo "Checking if docker-compose.yml exists before SCP..."
-          ls -l $(Build.SourcesDirectory)/docker-compose.yml || { echo "File not found!"; exit 1; }
+          # echo "Checking if docker-compose.yml exists before SCP..."
+          # ls -l $(Build.SourcesDirectory)/docker-compose.yml || { echo "File not found!"; exit 1; }
 
-          Use SCP with correct path
-          scp $(Build.SourcesDirectory)/docker-compose.yml user@vm-ip:/remote/destination/path
+          # Use SCP with correct path
+          # scp $(Build.SourcesDirectory)/docker-compose.yml user@vm-ip:/remote/destination/path
 
 - stage: DeployToVM
   displayName: 'Deploy Docker Image to VM'
